name: Master

on:
  push:
    branches:
      - 'master'

jobs:
  pylint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: "3.9"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pylint
      - name: Analysing the code with pylint
        run: |
          pylint $(ls -d */)
  docker:
    runs-on: ubuntu-latest
    needs: pylint
    steps:
      - uses: actions/checkout@master
      - name: Publish to Registry
        uses: elgohr/Publish-Docker-Github-Action@v5
        env:
          COMMIT: ${{ github.SHA }}
        with:
          name: mospolytech-solar-regatta/solar-tester/solar-tester
          username: ${{ github.ACTOR }}
          password: ${{ secrets.REGISTRY_TOKEN }}
          registry: docker.pkg.github.com
          tags: "latest,${{ github.SHA }}"
          buildargs: COMMIT
